"use client";

import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import Footer from './components/Footer'
import { usePathname } from 'next/navigation'
import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] });
import SearchContext from './components/Context';
import CarouselComponent from './components/CarouselComponent';
import NextTopLoader from 'nextjs-toploader';


export const metadata = {
  title: 'Optimum Nutrition',
  description: 'Generated by create next app',
}  

export default function RootLayout({ children, pageProps }) {
  const pathname = usePathname();
  const [searchValue, setsearchValue] = useState("");
  const [filterCategory,setfilterCategory]=useState("All");

  return (
    <html lang="en">
      <body >
        <SearchContext.Provider value={[searchValue, setsearchValue,filterCategory,setfilterCategory]}>
          <div className='mainlayout_container'>
            <NextTopLoader
              color="#2299DD"
              initialPosition={0.08}
              crawlSpeed={200}
              height={3}
              crawl={true}
              easing="ease"
              speed={200}
              shadow="0 0 10px #2299DD,0 0 5px #2299DD"
              template='<div class="bar" role="bar"><div class="peg"></div></div> 
                <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
              zIndex={1600}
              showAtBottom={false}
            />
            <Header />
            {pathname == "/" ? <CarouselComponent /> : null}
            <div className='sidebar_bodycomponent_div'>
              {pathname == "/" ? <Sidebar /> : null}
              {children}
            </div>
            <div className='footer_component_div'>
              <Footer />
            </div>
          </div>
        </SearchContext.Provider>
      </body>
    </html>
  )
}
